import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "lenis/dist/lenis.css";
import "./globals.css";
import SmoothScroll from "@/components/SmoothScroll";
import Navbar from "@/components/Navbar";
import Preloader from "@/components/Preloader";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* the browser's own scroll-restoration-on-reload is what causes a
            reload to snap back to whatever section you were scrolled to -
            turning it off here, before hydration, is the actual root cause
            fix (a reload then just starts at the top like any fresh
            navigation) rather than fighting it with a delayed scrollTo */}
        <Script id="disable-scroll-restoration" strategy="beforeInteractive">
          {"try{if('scrollRestoration' in history){history.scrollRestoration='manual';}}catch(e){}"}
        </Script>
        {/* unconditionally part of the server-rendered HTML - see the
            .preloader rule in globals.css and the comment on Preloader.jsx
            for why nothing here waits on JS/hydration to cover the Hero */}
        <Preloader />
        <SmoothScroll />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
